server:
  port: 8080

nacos:
  config:
    server-addr: localhost:8848
    namespace: 03b6dc11-e91a-4545-afec-c1db99fa705e
    group: DEFAULT_GROUP
    auto-refresh: true
    data-id: portal
    bootstrap:
      enable: true
      log-enable: true
    max-retry: 10
    type: yaml
