server:
  port: 8080

nacos:
  config:
    server-addr: data.iblogs.site:8848
    namespace: 03b6dc11-e91a-4545-afec-c1db99fa705e
    group: DEFAULT_GROUP
    auto-refresh: true
    data-id: portal
    bootstrap:
      enable: true
      log-enable: true
    type: properties
    max-retry: 10
