server:
  port: 8080

nacos:
  config:
    server-addr: omv:8848
    namespace: 03b6dc11-e91a-4545-afec-c1db99fa705a
    group: DEFAULT_GROUP
    auto-refresh: true
    data-id: portal
    bootstrap:
      enable: true
      log-enable: false
    max-retry: 10
    type: yaml

logging:
  config: classpath:logback-spring.xml
