server:
  port: 8080

nacos:
  config:
    server-addr: data.iblogs.site:8848
    namespace: f1426bb3-51c1-487e-8e0a-c33c7c31fad5
    group: DEFAULT_GROUP
    auto-refresh: true
    data-id: portal
    bootstrap:
      enable: true
      log-enable: false
    max-retry: 10
    type: yaml
