server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://iblogs:3307/iblogs?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: dev
    password: 123456

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
