apiVersion: v1
kind: Namespace
metadata:
  name: mybox
---
apiVersion: v1
kind: Service
metadata:
  name: iblogs-portal
  namespace: mybox
spec:
  selector:
    app: iblogs-portal
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iblogs-portal
  namespace: mybox
spec:
  selector:
    matchLabels:
      app: iblogs-portal
  replicas: 2
  minReadySeconds: 5
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: iblogs-portal
    spec:
      containers:
        - name: iblogs
          image: liuzhenyulive/iblogs:67
          args:
            [
              "--nacos.config.namespace=03b6dc11-e91a-4545-afec-c1db99fa705e"
            ]
          ports:
            - containerPort: 8080
              name: iblogs-portal
