apiVersion: v1
kind: Namespace
metadata:
  name: mybox
---
apiVersion: v1
kind: Service
metadata:
  name: iblogs-portal
  namespace: mybox
spec:
  selector:
    app: iblogs-portal
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iblogs-portal
  namespace: mybox
spec:
  selector:
    matchLabels:
      app: iblogs-portal
  replicas: 2
  minReadySeconds: 5
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: iblogs-portal
    spec:
      containers:
        - name: iblogs
          image: liuzhenyulive/iblogs:50
          args:
            [
              "--spring.datasource.url=jdbc:mysql://omv:3306/iblogs?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai",
              "--spring.redis.host=omv",
              "--ftp.username=iblogs/dev-iblogs-web",
              "--ftp.password=MgQjuVGoocDQZQHBVngUr627ACCzwkuw",
              "--upYun.backetname=dev-iblogs-web",
              "--upYun.password=MgQjuVGoocDQZQHBVngUr627ACCzwkuw",
            ]
          ports:
            - containerPort: 8080
              name: iblogs-portal
