apiVersion: v1
kind: Namespace
metadata:
  name: mybox
---
apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: mybox
spec:
  selector:
    app: nacos
  type: NodePort
  ports:
    - port: 8848
      targetPort: 8848
      nodePort: 30848
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
  namespace: mybox
data:
  mysql.db.host: 192.168.101.4
  mysql.db.name: "nacos"
  mysql.port: "3306"
  mysql.user: "dev"
  mysql.password: "123456"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: mybox
spec:
  selector:
    matchLabels:
      app: nacos
  replicas: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
        - name: nacos
          image: nacos/nacos-server
          env:
            - name: MODE
              value: "standalone"
            - name: SPRING_DATASOURCE_PLATFORM
              value: "mysql"
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.host
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.password
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.name
            - name: JVM_XMS
              value: "512m"
            - name: JVM_XMX
              value: "512m"
            - name: JVM_XMN
              value: "256m"

          ports:
            - containerPort: 8848
              name: nacos
