name: dev

on:
  push:
    branches: [dev]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        run: mvn -B clean verify -Pintegration-Test

  docker:
    name: Publish - AliYun Docker Hub
    runs-on: ubuntu-latest
    needs: [test]

    steps:
    - name: publish container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PRODHOST }}
        username: ${{ secrets.PRODUSERNAME }}
        password: ${{ secrets.PRODPASSWORD }}
        port: ${{ secrets.PRODPORT }}
        command_timeout: 30m
        script: |
          yum install git -y
          DIR="/docker/workspace"
          mkdir -p $DIR
          cd $DIR
          if [ -d "$DIR/iBlogs" ]; then
            cd $DIR/iBlogs
            git checkout dev
            git pull
          else
            git clone https://github.com/liuzhenyulive/iBlogs.git
            cd $DIR/iBlogs
            git checkout dev
          fi
          docker build -f ${{ secrets.DOCKER_REPO }}:${{ github.run_number }} .
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          docker push registry.cn-hangzhou.aliyuncs.com/${{ secrets.DOCKER_REPO }}:${{ github.run_number }}

  deploy:
    name: deploy container on k8s
    runs-on: ubuntu-latest
    needs: [docker]

    steps:

    - name: deploy container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PRODHOST }}
        username: ${{ secrets.PRODUSERNAME }}
        password: ${{ secrets.PRODPASSWORD }}
        port: ${{ secrets.DEV_SSH_PORT }}
        command_timeout: 30m
        script: |
          kubectl set image --record deployment/iblogs-portal iblogs=registry.cn-hangzhou.aliyuncs.com/${{ secrets.DOCKER_REPO }}:${{ github.run_number }} -n mybox